on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: v19.9.0
          cache: npm
      - name: Install npm
        run: npm ci
      - name: Run unit tests
        run: npm run test:unit
      - name: Install playwright
        run: npx playwright install --with-deps
      - name: Run browser tests
        run: npm run test
